[tool]
[tool.poetry]
name = "MiaUserbot_Deployer"
version = "1.0"
description = "Automatic Deploy MiaUserBot to Heroku"
authors = ["Miaub"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
