[tool]
[tool.poetry]
name = "EpicUserbot_Deployer"
version = "1.0"
description = "Automatic Deploy EpicUserBot to Heroku"
authors = ["ErdemBey"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
